import React from 'react'
import styles from "../../Proyectos/Proyectos.module.css"

export const MoreProject = () => {
  return (
    <div>
        <h1 className='font-mono text-2xl bg-blue-400 text-center'>MoreProject</h1>
        <div className={styles.ls}>
            <div className='flex flex-col h-96 w-10'>OKKKKKKKKKKKKKKKKKKKOKKKKKKKKKKKKKKKKKKKOKKKKKKKKKKKKKKKKKKKOKKKKKKKKKKKKKKKKKKKOKKKKKKKKKKKKKKKKKKKOKKKKKKKKKKKKKKKKKKKOKKKKKKKKKKKKKKKKKKK</div>
            <div className='flex flex-col h-96 w-20'>OKKKKKKKKKKKKKKKKKKKOKKKKKKKKKKKKKKKKKKKOKKKKKKKKKKKKKKKKKKKOKKKKKKKKKKKKKKKKKKKOKKKKKKKKKKKKKKKKKKKOKKKKKKKKKKKKKKKKKKKOKKKKKKKKKKKKKKKKKKK</div>
            <div className='flex flex-col h-96 w-20'>OKKKKKKKKKKKKKKKKKKKOKKKKKKKKKKKKKKKKKKKOKKKKKKKKKKKKKKKKKKKOKKKKKKKKKKKKKKKKKKKOKKKKKKKKKKKKKKKKKKKOKKKKKKKKKKKKKKKKKKKOKKKKKKKKKKKKKKKKKKK</div>
            <div className='flex flex-col h-96 w-20'>OKKKKKKKKKKKKKKKKKKKOKKKKKKKKKKKKKKKKKKKOKKKKKKKKKKKKKKKKKKKOKKKKKKKKKKKKKKKKKKKOKKKKKKKKKKKKKKKKKKKOKKKKKKKKKKKKKKKKKKKOKKKKKKKKKKKKKKKKKKK</div>
            <div className='flex flex-col h-96 w-20'>OKKKKKKKKKKKKKKKKKKKOKKKKKKKKKKKKKKKKKKKOKKKKKKKKKKKKKKKKKKKOKKKKKKKKKKKKKKKKKKKOKKKKKKKKKKKKKKKKKKKOKKKKKKKKKKKKKKKKKKKOKKKKKKKKKKKKKKKKKKK</div>
            <div className='flex flex-col h-96 w-20'>OKKKKKKKKKKKKKKKKKKKOKKKKKKKKKKKKKKKKKKKOKKKKKKKKKKKKKKKKKKKOKKKKKKKKKKKKKKKKKKKOKKKKKKKKKKKKKKKKKKKOKKKKKKKKKKKKKKKKKKKOKKKKKKKKKKKKKKKKKKK</div>
        </div>
    </div>

  )
}
